###
POST http://localhost:8080/users

{
    "username": "helloWin",
    "password": "12345678",
    "full_name": "Sunil Gong",
    "email": "abc2@123.com"
}


###
POST http://localhost:8080/accounts

{
    "owner": "kawjjk",
    "currency": "EUR"
}

###
http://localhost:8080/accounts?page_id=6&page_size=5

###
PUT  http://localhost:8080/accounts

{
    "id": 236,
    "balance": 10
}
###
DELETE  http://localhost:8080/accounts

{
    "id": 237
}

###
POST http://localhost:8080/transfers

{
    "from_account_id": 778,
    "to_account_id": 779,
    "amount": 1,
    "currency": "DDD"
}