###
POST http://localhost:8080/accounts

{
    "owner": "Sunil",
    "currency": "USD"
}

###
http://localhost:8080/accounts?page_id=6&page_size=5

###
PUT  http://localhost:8080/accounts

{
    "id": 236,
    "balance": 10
}
###
DELETE  http://localhost:8080/accounts

{
    "id": 237
}