###
POST http://localhost:8080/users

{
    "username": "helloWin",
    "password": "12345678",
    "full_name": "Sunil Gong",
    "email": "abc2@123.com"
}

###
POST http://localhost:8080/users/login

{
    "username": "helloMAC",
    "password": "12345678"
}




###
POST http://localhost:8080/accounts
Authorization: Bearer v2.local._AsIjqtMrGB3EdNf1kxesrIQXzwcX50vnMqUhgPqHPKLkoZIvyCmfqLWWfS14O-JC-aRIKPJUr1O-zTzJNbHQGFxpviRL2VElkUwTX5nJpQSas3i10AOBawm9483IPqxpTHCqXgc8Nw7E5f4S4O0HJWoc_kc_h9yV9BWrj7OsHDcv3bkF96LU27xHoZj5w7bf78XgfGaI_SW5uw_pW6bYtsHKzDS1Sj6khQkqxq_Ff-p49g38l2yisid1ewEmN_p4waSYhV86Wzh3w.bnVsbA

{
    "owner": "helloMAC",
    "currency": "EUR"
}

###
http://localhost:8080/accounts?page_id=1&page_size=5
Authorization: Bearer v2.local._AsIjqtMrGB3EdNf1kxesrIQXzwcX50vnMqUhgPqHPKLkoZIvyCmfqLWWfS14O-JC-aRIKPJUr1O-zTzJNbHQGFxpviRL2VElkUwTX5nJpQSas3i10AOBawm9483IPqxpTHCqXgc8Nw7E5f4S4O0HJWoc_kc_h9yV9BWrj7OsHDcv3bkF96LU27xHoZj5w7bf78XgfGaI_SW5uw_pW6bYtsHKzDS1Sj6khQkqxq_Ff-p49g38l2yisid1ewEmN_p4waSYhV86Wzh3w.bnVsbA

###
PUT  http://localhost:8080/accounts

{
    "id": 236,
    "balance": 10
}
###
DELETE  http://localhost:8080/accounts

{
    "id": 237
}

###
POST http://localhost:8080/transfers
Authorization: Bearer v2.local._AsIjqtMrGB3EdNf1kxesrIQXzwcX50vnMqUhgPqHPKLkoZIvyCmfqLWWfS14O-JC-aRIKPJUr1O-zTzJNbHQGFxpviRL2VElkUwTX5nJpQSas3i10AOBawm9483IPqxpTHCqXgc8Nw7E5f4S4O0HJWoc_kc_h9yV9BWrj7OsHDcv3bkF96LU27xHoZj5w7bf78XgfGaI_SW5uw_pW6bYtsHKzDS1Sj6khQkqxq_Ff-p49g38l2yisid1ewEmN_p4waSYhV86Wzh3w.bnVsbA

{
    "from_account_id": 124,
    "to_account_id": 779,
    "amount": 1,
    "currency": "EUR"
}